apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: test
        image: stevelee0910/task5.1:latest
        ports:
        - containerPort: 8080
