apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    run: test
spec:
  containers:
  - image: stevelee0910/task5.1:latest
    name: test
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
